var ReservationFilterConstants = {
  RESERVATION_FILTERS_RECEIVED: "RESERVATION_FILTERS_RECEIVED",
  RESERVATION_OPTIONS_RECEIVED: "RESERVATION_OPTIONS_RECEIVED"
};

module.exports = ReservationFilterConstants;
