var RestaurantConstants = {
  RESTAURANTS_RECEIVED: "RESTAURANTS_RECEIVED",
  RESTAURANT_RECEIVED: "RESTAURANT_RECEIVED",
  RESULTS_RECEIVED: "RESULTS_RECEIVED"
};

module.exports = RestaurantConstants;
